name: CI/CD

on:
  push:
    branches:
      - develop

jobs:
  build:
    environment: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Run tests
        run: |
          chmod +x ./gradlew   
          ./gradlew test
        env:
          SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
          IMP_CODE: ${{ secrets.IMP_CODE }}
          IMP_API_KEY: ${{ secrets.IMP_API_KEY }}
          IMP_API_SECRETKEY: ${{ secrets.IMP_API_SECRETKEY }}

